woman(lisa).
woman(tami).
woman(frances).
woman(allison).
woman(debbie).
woman(elliot).
woman(fiona).
woman(carla).
woman(jordan).
woman(hannah).
woman(jessica).
woman(mabel).
woman(cersei).
woman(sansa).

man(gregory).
man(lip).
man(frank).
man(robert).
man(liam).
man(john).
man(christopher).
man(percival).
man(ian).
man(clay).
man(lucifer).
man(dean).
man(sam).
man(dipper).
man(tiryon).

parent(hannah,lucifer).
parent(clay,lucifer).
parent(sansa,fiona).
parent(sansa,ian).
parent(tiryon,fiona).
parent(tiryon,ian).
parent(lisa,allison).
parent(lisa,robert).
parent(gregory,allison).
parent(gregory,robert).
parent(tami,liam).
parent(lip,liam).
parent(frances,debbie).
parent(frances,john).
parent(frank,debbie).
parent(frank,john).
parent(mabel,daenerys).
parent(dipper,daenerys).
parent(lucifer,dean).
parent(lucifer,sam).
parent(fiona,dean).
parent(fiona,sam).
parent(ian,carla).
parent(ian,jordan).
parent(ian,jessica).
parent(allison,carla).
parent(allison,jordan).
parent(allison,jessica).
parent(liam,elliot).
parent(liam,christopher).
parent(liam,percival).
parent(debbie,elliot).
parent(debbie,christopher).
parent(debbie,percival).
parent(john,cersei).
parent(daenerys,cersei).